from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime

class ContentItem(BaseModel):
    id: Optional[str] = Field(None, description="Unique identifier for the content item")
    user_id: int = Field(..., description="Telegram User ID")
    source_type: str = Field(..., description="Type of source content (e.g., 'text', 'voice')")
    source_content: str = Field(..., description="Original content or URL to original content")
    generated_text: Optional[str] = Field(None, description="Text generated by Claude")
    video_url: Optional[str] = Field(None, description="URL to the generated video")
    status: str = Field(default="pending", description="Current status of the content generation process")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    # TODO: Add more fields as necessary (e.g., target platform, template ID)
